[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5
maxMessageSize = 50
enableStaticServing = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"

[runner]
fastReruns = true
magicEnabled = false

[global]
developmentMode = false 